<a href="https://colab.research.google.com/github/RuslanHasiuk/Data_Profiling_Pandas-/blob/main/notebooks/Pandas_%F0%9F%90%BC_Workout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

üêº‚ú® Pandas Workout Level 1 ‚Äî Fundamentals

‚ö°Ô∏è Exercise 1: Create the Training Dataset

In [ ]:
import pandas as pd

In [ ]:
data = {
    'customer_id': [101, 102, 103, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fay'],
    'age': [25, 34, 45, None, 40, 23],
    'purchase_amount': [250.0, 150.5, 340.0, 129.99, 560.0, 80.75],
    'purchase_date': ['2023-01-15', '2023-01-17', '2023-01-18', '2023-01-20', '2023-01-22', '2023-01-25']
}

In [ ]:
df = pd.DataFrame(data)

üß† Exercise 2: Preview the Data

In [ ]:
df.head()

   customer_id     name   age  purchase_amount purchase_date
0          101    Alice  25.0           250.00    2023-01-15
1          102      Bob  34.0           150.50    2023-01-17
2          103  Charlie  45.0           340.00    2023-01-18
3          104    Diana   NaN           129.99    2023-01-20
4          105    Ethan  40.0           560.00    2023-01-22

üìä Exercise 3: Check Data Types

In [ ]:
df.dtypes

customer_id          int64
name                object
age                  int64
purchase_amount    float64
purchase_date       object
dtype: object

üß† Pandas Data Types Cheat Sheet

	‚Ä¢	int64: 64-bit integer (whole numbers)

	‚Ä¢	float64: 64-bit float (decimal numbers)

	‚Ä¢	object: generic type, usually for text (strings)

	‚Ä¢	string: dedicated string type (use when sure it‚Äôs only text)

	‚Ä¢	bool: True/False

	‚Ä¢	datetime64: date & time values

	‚Ä¢	category: for repeated text values (saves memory)

üëâ Use .dtypes to check column types
üëâ Use .astype() to convert types

In [ ]:
df.nunique()

customer_id        6
name               6
age                5
purchase_amount    6
purchase_date      6
dtype: int64

üî¢ Exercise 4: How many unique customers?

In [ ]:
df['customer_id'].nunique()

6

üí∏ Exercise 5: What‚Äôs the average purchase amount?

In [ ]:
df['purchase_amount'].agg(['min', 'max', 'mean'])

min      80.750000
max     560.000000
mean    251.873333
Name: purchase_amount, dtype: float64

# ü•á Find the row of the customer with the highest purchase
df.loc[df['purchase_amount'].idxmax()]

In [ ]:
df['customer_id'].idxmax()

5

In [ ]:
df.loc[df['purchase_amount'].idxmax()]

customer_id               105
name                    Ethan
age                      40.0
purchase_amount         560.0
purchase_date      2023-01-22
Name: 4, dtype: object

In [ ]:
df.sort_values('purchase_amount', ascending=False).head(1)

   customer_id   name   age  purchase_amount purchase_date
4          105  Ethan  40.0            560.0    2023-01-22

üêºüî• Pandas Workout Level 2 ‚Äî Filtering, Grouping, **Dates**

In [ ]:
df.head()

   customer_id     name   age  purchase_amount purchase_date
0          101    Alice  25.0           250.00    2023-01-15
1          102      Bob  34.0           150.50    2023-01-17
2          103  Charlie  45.0           340.00    2023-01-18
3          104    Diana   NaN           129.99    2023-01-20
4          105    Ethan  40.0           560.00    2023-01-22

üßπ Exercise 1: Filter customers under 30

In [ ]:
df['age'] < 30 # Checks Boolean

0     True
1    False
2    False
3    False
4    False
5     True
Name: age, dtype: bool

In [ ]:
df[df['age'] < 30] # Return RECORDS

   customer_id   name   age  purchase_amount purchase_date
0          101  Alice  25.0           250.00    2023-01-15
5          106    Fay  23.0            80.75    2023-01-25

üéØ Exercise 2: Who spent üí∞ more than 300?

In [ ]:
df[df['purchase_amount'] > 300]

   customer_id     name   age  purchase_amount purchase_date
2          103  Charlie  45.0            340.0    2023-01-18
4          105    Ethan  40.0            560.0    2023-01-22

üß† Exercise 3: Average spend by age group

In [ ]:
# üë• Group by age and calculate average purchase
df.groupby('age')['purchase_amount'].mean()

age
23.0     80.75
25.0    250.00
34.0    150.50
40.0    560.00
45.0    340.00
Name: purchase_amount, dtype: float64

üóìÔ∏è Exercise 4: Convert purchase_date to datetime

In [ ]:
df['purchase_date'].astype('datetime64[ms]')

0   2023-01-15
1   2023-01-17
2   2023-01-18
3   2023-01-20
4   2023-01-22
5   2023-01-25
Name: purchase_date, dtype: datetime64[ms]

Option #2 -- üß† RECOMMENDED !!! üß†

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

‚úÖ Benefits of pd.to_datetime():

	‚Ä¢	üîç Auto-detects common date formats

	‚Ä¢	üõ°Ô∏è Handles errors gracefully with errors='coerce'

	‚Ä¢	üîÑ Parses mixed date formats in the same column

	‚Ä¢	‚ö°Ô∏è Faster and safer for large datasets
  
	‚Ä¢	üß† Supports time zone conversions and datetime operations

üìÜ Exercise 5: Filter purchases after January 20, 2023

In [ ]:
df[df['purchase_date'] > '2023-01-20']

   customer_id   name   age  purchase_amount purchase_date
4          105  Ethan  40.0           560.00    2023-01-22
5          106    Fay  23.0            80.75    2023-01-25

üí° Bonus: Add a new column with day of week

In [ ]:
# üóìÔ∏è Add column for day name (e.g., Monday)
df['day_of_week'] = df['purchase_date'].dt.day_name()
df[['name', 'purchase_date', 'day_of_week']]

      name purchase_date day_of_week
0    Alice    2023-01-15      Sunday
1      Bob    2023-01-17     Tuesday
2  Charlie    2023-01-18   Wednesday
3    Diana    2023-01-20      Friday
4    Ethan    2023-01-22      Sunday
5      Fay    2023-01-25   Wednesday

In [ ]:
df.dtypes

customer_id                 int64
name                       object
age                       float64
purchase_amount    datetime64[ns]
purchase_date      datetime64[ns]
day_of_week                object
dtype: object

! OOPs! A cidently üîÅ purchase_amount column i casted to datetime :)

Let's fix it

In [ ]:
df['purchase_amount'] = pd.to_numeric(df['purchase_amount'], errors='coerce')

In [ ]:
df.dtypes

customer_id                 int64
name                       object
age                       float64
purchase_amount             int64
purchase_date      datetime64[ns]
day_of_week                object
dtype: object

üêºüî• Pandas Workout Level 3:

 Chaining

 Lambdas

 Conditional Logic

üß™ Exercise 1 üß™: Add a ‚ÄúHigh Spender‚Äù column

We‚Äôll add a new column that says "Yes" if someone spent more than 300, otherwise "No".

‚öôÔ∏è Exercise 2: Chain it all together

üß† Exercise 3: Create custom age group

‚ö†Ô∏è Exercise 4: Multiple conditions with np.where()

üéÅ Bonus: Query method ‚Äî SQL-style filtering